name: 'Run the test case built in Cypress.io'
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install Cypress Cucumber Preprocessor
        run: npm install --save-dev cypress-cucumber-preprocessor
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome