name: 'Hello world from JS Action'
on: push
runs-on: ubuntu-latest
jobs:
  deploy:
    name: Run the test using Cypress.io
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
    