name: 'Hello world from JS Action'
description: 'Greet someone and record the time'
on: push
jobs:
  deploy:
    name: Run the test using Cypress.io
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
    