name: 'Run the test case built in Cypress.io'
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install cypress.io
        run: npm install --save-dev cypress
      - name: Install Cypress Cucumber Preprocessor
        run: npm install --save-dev cypress-cucumber-preprocessor
      - name: Run the test case
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome